package ca.bc.gov.educ.api.student.profile.email.constants;

public enum EventType {
  NOTIFY_STUDENT_PROFILE_REQUEST_COMPLETE, NOTIFY_STUDENT_PROFILE_REQUEST_RETURN, NOTIFY_STUDENT_PROFILE_REQUEST_REJECT,
  PROFILE_REQUEST_EMAIL_API_EVENT_OUTBOX_PROCESSED
}
