CREATE TABLE STUDENT_PROFILE_REQUEST_EMAIL_EVENT
(
    EVENT_ID      UUID                                NOT NULL,
    EVENT_PAYLOAD VARCHAR(4000)                       NOT NULL,
    EVENT_STATUS  VARCHAR                             NOT NULL,
    EVENT_TYPE    VARCHAR                             NOT NULL,
    SAGA_ID       UUID,
    EVENT_OUTCOME VARCHAR                             NOT NULL,
    REPLY_CHANNEL VARCHAR,
    CREATE_USER   VARCHAR(32)                         NOT NULL,
    CREATE_DATE   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER   VARCHAR(32)                         NOT NULL,
    UPDATE_DATE   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT STUDENT_PROFILE_REQUEST_EMAIL_EVENT_PK PRIMARY KEY (EVENT_ID)
);
CREATE INDEX STUDENT_PROFILE_REQUEST_EMAIL_EVENT_EVENT_STATUS_IDX ON STUDENT_PROFILE_REQUEST_EMAIL_EVENT (EVENT_STATUS);
CREATE INDEX STUDENT_PROFILE_REQUEST_EMAIL_EVENT_SAGA_ID_IDX ON STUDENT_PROFILE_REQUEST_EMAIL_EVENT (SAGA_ID);
CREATE INDEX STUDENT_PROFILE_REQUEST_EMAIL_EVENT_EVENT_TYPE_IDX ON STUDENT_PROFILE_REQUEST_EMAIL_EVENT (EVENT_TYPE);


CREATE TABLE STUDENT_PROFILE_REQUEST_EMAIL_SHEDLOCK
(
    NAME       VARCHAR(64),
    LOCK_UNTIL TIMESTAMP(3) NULL,
    LOCKED_AT  TIMESTAMP(3) NULL,
    LOCKED_BY  VARCHAR(255),
    CONSTRAINT STUDENT_PROFILE_REQUEST_EMAIL_SHEDLOCK_PK PRIMARY KEY (NAME)
);
COMMENT ON TABLE STUDENT_PROFILE_REQUEST_EMAIL_SHEDLOCK IS 'This table is used to achieve distributed lock between pods, for schedulers.';

