---
apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: 'educ-student-profile-email-api-template'
metadata:
  name: 'educ-student-profile-email-api-template'
objects:
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      labels:
        build: educ-student-profile-email-api-pipeline
      name: educ-student-profile-email-api-pipeline
    spec:
      source:
        git:
          ref: master
          uri: 'https://github.com/bcgov/EDUC-STUDENT-PROFILE-EMAIL-API'
        type: Git
      strategy:
        jenkinsPipelineStrategy:
          jenkinsfilePath: tools/Jenkins/Jenkinsfile